#!/bin/bash
# PN TOOL REJOIN - Setup Script (Full Support Root & Python 3.13)

# 1. Cấp quyền & Cập nhật hệ thống
termux-setup-storage
sleep 2

echo "Dang cap nhat he thong..."
pkg update -y && pkg upgrade -y

# 2. Cài đặt Python, Curl và TSU (Để chạy Root)
echo "Dang cai dat Python & Root Tool..."
pkg install python curl tsu -y

# 3. Cài đặt thư viện requests
echo "Dang cai dat thu vien..."
pip install requests

# 4. Tải Tool
FILE_PATH="/sdcard/Download/pn.py"
DOWNLOAD_URL="https://raw.githubusercontent.com/PhuNguyenToolRejoin/pn-rejoin/main/main.py"

echo "Dang tai tool..."
curl -L -o "$FILE_PATH" "$DOWNLOAD_URL"

if [ -f "$FILE_PATH" ]; then
    echo "------------------------------------------"
    echo "    DA CAI DAT XONG TOOL REJOIN BY PN     "
    echo "    Yeu cau: May da Root (Magisk/KSU)     "
    echo "    Lenh chay: Xem tai Discord            "
    echo "------------------------------------------"
else
    echo "Loi: Khong the tai file!"
fi
